### ISSUE TITLE
OpenStudio-Standards uses OpenStudio::Workflow.run_energyplus which is missing on the OSW branch

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio-workflow-gem#31]
https://github.com/NREL/openstudio-standards/blob/7d32e8ed3de795c6ebd9e2b2730fc4ec5a8fdaff/openstudio-standards/lib/openstudio-standards/utilities/simulation.rb#L84

**Comment by macumber** [comment]
Should add a test that runs the Prototype measure and then a simulation.  This is more of an integration test, maybe we need another repo for those?

**Comment by rHorsey** [comment]
I want to add this anyway so we can test a no-osm case. The other option would be to import the osm or idf instead of embedding the prototype measure. Thoughts @macumber ?

**Comment by macumber** [comment]
Well the idea of the test would be to test that you can load the standards gem and run all the api methods that the prototype measure uses.

**Comment by rHorsey** [comment]
I've implemented and tested new code for it. You can see it at https://github.com/NREL/openstudio-standards/pull/61. Once it's been vetted it should hopefully be merged in. Until then I'd recommend using my fork.
