### ISSUE TITLE
No root property in osw

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio-workflow-gem#35]
@rHorsey I thought there was a 'root' property in osw, it is in this description https://docs.google.com/document/d/1PYL-vPMEMgsZdATlUh6ZbVatdf7zSl3g460Xyx7B-Zc/edit#heading=h.4r6vf2s04y9t

However, it isn't in the schema or tests.  Can I go ahead and add it?

**Comment by rHorsey** [comment]
Ya. Please do. This falls into my not doing a good job a keeping the osw schema version tracking our work. Sorry!
