### ISSUE TITLE
Simulation of Solar tracking shading devices (Integrated with PV)

### ISSUE THREAD

**Issue by HardiBarznji** [NREL/OpenStudio-workflow-gem#71]
Hi everyone,

I am trying to simulate a model of dual axis solar tracking shading device (integrated with PV) **to calculate the amount of electricity produced from the PV also the shading performance of the tracking shading devices**. 
I have used OpenStudio SketchUp Plugin to model the building and simulate the energy performance of the building using OpenStudio software, but now I need to model and simulate this tracking system of **PV-Integrated two-axis solar tracking shading device**, is it possible to perform this in OpenStudio or API? If so, how can I perform this task? This is not a static system as you know and it should be responding to the Sun's movement during the simulation runtime period.
Thank you in advance

**Comment by macumber** [comment]
This is the wrong repo for this issue.  I suggest you post this question to unmethours.com
